language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
dist: xenial
addons:
  apt:
    packages:
      - libsodium18
      - graphviz
      - bind9
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - python tests/offline_tests.py
  - python tests/online_tests.py
